# Exploración Archivos Google maps
Se busca entender la naturaleza, formato y estructura que contienen los archivos de metadatada de google maps para luego realizar un proceso de ETL.

In [15]:
#Importamos las librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [16]:
#leemos el archivo en formato json
dir = ('data\metadata-sitios/1.json')
uno = pd.read_json(dir,lines=True)

In [17]:
#Se observa el dataframe
uno.sample(5)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
48445,Brooklyn House of Detention,"Brooklyn House of Detention, 275 Atlantic Ave,...",0x89c25a4e7d2df4e7:0xee6f98776a1bef80,None,40.688955,-73.989748,[Detention center],3.1,38,None,"[[Wednesday, 1–8PM], [Thursday, 1–8PM], [Frida...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 1PM,"[0x89c25aea922f76bf:0x1eb7d0f2e88b9e14, 0x89c2...",https://www.google.com/maps/place//data=!4m2!3...
101755,"Micah Blackmon, MD","Micah Blackmon, MD, 775 Poplar Rd Suite 160, N...",0x88e6d95d0b53824d:0xc32d995e06343e8a,None,33.356647,-84.754148,[Urologist],3.0,6,None,None,"{'Service options': ['Online care'], 'Accessib...",None,"[0x88f4c7c7982283d3:0x24767fa1ca720200, 0x88f4...",https://www.google.com/maps/place//data=!4m2!3...
219596,Comedy Playground,None,0x80c2b89d62c54723:0xd12d30d441e68b5d,None,33.811424,-118.178945,"[Class, Service establishment]",4.3,14,None,"[[Monday, 5PM–2AM], [Tuesday, 5PM–2AM], [Wedne...",None,Closed ⋅ Opens 5PM,"[0x80c2bf3b58569689:0xf685ffaa9ca0c0ff, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
85259,Cox Canyon,"Cox Canyon, Nevada",0x80a25d5ee709b837:0x851593b6d3dd538e,None,39.697694,-118.295970,[Ravine],5.0,1,None,None,None,None,None,https://www.google.com/maps/place/Nevada/data=...
179719,Crystal Clear Water,"Crystal Clear Water, 935 W 240th St NE, North ...",0x87e45b45f9dd3cf5:0x8ad393eab63dd0c3,None,41.759062,-91.611964,"[Bottled water supplier, Water softening equip...",5.0,48,None,"[[Wednesday, 8AM–5PM], [Thursday, 8AM–5PM], [F...",None,Closed ⋅ Opens 8AM,"[0x87e44445350e1461:0xa2f970a0daa8c7b4, 0x87e4...",https://www.google.com/maps/place//data=!4m2!3...

In [18]:
#Obtenemos informacion del dataframe
uno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275001 entries, 0 to 275000
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   name              274994 non-null  object
 1   address           264939 non-null  object
 2   gmap_id           275001 non-null  object
 3   description       13155 non-null   object
 4   latitude          275001 non-null  float64
 5   longitude         275001 non-null  float64
 6   category          272740 non-null  object
 7   avg_rating        275001 non-null  float64
 8   num_of_reviews    275001 non-null  int64
 9   price             13450 non-null   object
 10  hours             192448 non-null  object
 11  MISC              194972 non-null  object
 12  state             195523 non-null  object
 13  relative_results  238771 non-null  object
 14  url               275001 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 31.5+ MB

In [19]:
#Se decide observar la columna "Category" con detenimiento.

In [20]:
#Se crea la variable que nos muestre las categorias
category = uno['category'].dropna().explode()
#Se guardan las categorias unicas en la variable.
category = pd.Series(category.unique())

category

0                   Pharmacy
1           Textile exporter
2          Korean restaurant
3               Fabric store
4                 Restaurant
                ...
3764    Line marking service
3765       Windsurfing store
3766       Military barracks
3767                Helpline
3768    Cane furniture store
Length: 3769, dtype: object

In [21]:
#Se convierten el tipo de datos de la columna category en str
uno['category'] = uno['category'].str.replace(r' | ','',regex =True)

In [22]:
#se lee el domuneto numero dos
dir = ('data\metadata-sitios/2.json')
dos = pd.read_json(dir,lines = True)

In [23]:
#Observamos el dataframe "dos"
dos.sample(5)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
178938,East Ridgelawn Cemetery,"East Ridgelawn Cemetery, 255 Main Ave, Clifton...",0x89c2ff43a7deef99:0x6428a348bfd298fe,None,40.835906,-74.140479,[Cemetery],3.8,8,None,"[[Saturday, 8AM–5:30PM], [Sunday, 8AM–5:30PM],...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 8AM,"[0x89c2ff0def1b03ad:0xfa47f2b219b52a4e, 0x89c2...",https://www.google.com/maps/place//data=!4m2!3...
247733,Odezza,"Odezza, Santee Alley, Los Angeles, CA 90015",0x80c2c7ccf2986c3d:0x328f8b0598a98b34,None,34.038173,-118.254894,[Clothing store],5.0,1,None,"[[Wednesday, 10AM–6PM], [Thursday, 10AM–6PM], ...","{'Service options': ['In-store shopping'], 'Ac...",Open ⋅ Closes 6PM,"[0x80c2c7cdb6d350b3:0xbcbc8f5202a6f2bb, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
256738,Scarey's Powersports,"Scarey's Powersports, 19 N Niangua Ave, Camden...",0x87c4de5d84d59aab:0x42e8f3f9ab43c6a5,None,38.009411,-92.745167,[Motorcycle repair shop],4.2,25,None,"[[Wednesday, 8AM–6PM], [Thursday, 8AM–6PM], [F...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 8AM,"[0x87c4dee452186033:0x30c980933e12ac2f, 0x87c4...",https://www.google.com/maps/place//data=!4m2!3...
59820,Tulcingo Bakery,"Tulcingo Bakery, 2483 Jerome Ave, Bronx, NY 10468",0x89c2f38878123c05:0x94e77943a9e016bb,None,40.863648,-73.900678,[Bakery],3.1,28,None,None,{'Service options': ['Delivery']},None,"[0x89c2f30b7c0366f7:0x73d271d39a090d51, 0x89c2...",https://www.google.com/maps/place//data=!4m2!3...
179070,Home Health Pharmacy,"Home Health Pharmacy, 700 West Ave S, La Cross...",0x87f95512b7fe1f65:0x299688fa03916b7e,None,43.804000,-91.241731,[Pharmacy],4.0,1,None,"[[Friday, 9AM–5:30PM], [Saturday, Closed], [Su...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 9AM Mon,"[0x87f9552aff19945f:0x8de3fbba12e8625d, 0x87f9...",https://www.google.com/maps/place//data=!4m2!3...

In [24]:
#Obtenemos la informacion del dataframe

dos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275001 entries, 0 to 275000
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   name              274993 non-null  object
 1   address           265201 non-null  object
 2   gmap_id           275001 non-null  object
 3   description       14111 non-null   object
 4   latitude          275001 non-null  float64
 5   longitude         275001 non-null  float64
 6   category          272882 non-null  object
 7   avg_rating        275001 non-null  float64
 8   num_of_reviews    275001 non-null  int64
 9   price             14401 non-null   object
 10  hours             192124 non-null  object
 11  MISC              197827 non-null  object
 12  state             195942 non-null  object
 13  relative_results  241166 non-null  object
 14  url               275001 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 31.5+ MB

In [32]:
#Se crea la variable que nos muestre las categorias
category2 = dos['category'].dropna().explode()
#Se guardan las categorias unicas en la variable.
category2 = pd.Series(category2.unique())

category2

0                                 Pharmacy
1                           Clothing store
2                               Shoe store
3                   Women's clothing store
4       Handicapped transportation service
                       ...
3776                     Accounting school
3777                 Bungee jumping center
3778                    City pillar shrine
3779                       Coat wholesaler
3780                 Fire fighters academy
Length: 3781, dtype: object